name: CTF Level 3 - Hard
version: "1.0.0"
slug: ctf_level3
description: "Good luck."
url: "https://github.com/<YOUR_USERNAME>/<YOUR_REPO>/tree/main/ctf-nivel-dificil"
arch:
  - aarch64
  - amd64
init: false
image: "ghcr.io/thurmiel/{arch}-ctf-nivel-dificil"
apparmor: false
map:
  - type: share
    read_only: false
options:
  attacker_ip: "192.168.1.100"
  attacker_port: 4444

schema:
  attacker_ip: "str"
  attacker_port: "int"