# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Workshop Test
version: "2.0.0"
slug: workshoptest
description: A workshop test add-on
url: "https://github.com/<YOUR_USERNAME>/<YOUR_REPO>/tree/main/workshoptest"
arch:
  - aarch64
  - amd64
init: false
image: "ghcr.io/thurmiel/{arch}-workshoptest"
options:
  message: "Hello world..."
schema:
  message: "str?"
privileged:
  - BPF
  - CHECKPOINT_RESTORE
  - DAC_READ_SEARCH
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
  - PERFMON
  - SYS_ADMIN
  - SYS_MODULE
  - SYS_NICE
  - SYS_PTRACE
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_TIME
host_network: true
host_ipc: true # Allow the IPC namespace to be shared with others.
hassio_role: admin
hassio_api: true
homeassistant_api: true
docker_api: true
full_access: true
apparmor: false
map:
  - type: homeassistant_config
    read_only: false

  - type: addon_config
    read_only: false

  - type: ssl
    read_only: false

  - type: addons
    read_only: false

  - type: backup
    read_only: false

  - type: share
    read_only: false

  - type: media
    read_only: false

  - type: all_addon_configs
    read_only: false

  - type: data
    read_only: false