name: Build Add-ons

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon:
          - workshoptest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build add-on
        uses: home-assistant/builder@2025.11.0
        with:
          args: |
            --test \
            --aarch64 \
            --amd64 \
            --target /data/${{ matrix.addon }}
